server:
  port: 4004 # Gateway listens on port 4004

spring:
  cloud:
    gateway:
      routes:
        # Route for /api/patients/** to patient-service
        - id: post-service-route
          uri: http://Post-Service:4000
          predicates:
            - Path=/api/posts/**
          filters:
            - StripPrefix=1