### GET request to get all posts
GET http://localhost:4000/posts

###

POST http://localhost:4000/posts
Content-Type: application/json

{
  "title": "John Doe Kafka Test",
  "content": "kafka_test11@example.com",
  "author": "123 main street22"
}